
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
sensor: !include_dir_merge_list sensors/
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml

recorder:
  purge_keep_days: 365
  include:
    entities:
      - sensor.28_041685abbeff_temperature
      - sensor.day_min
      - sensor.day_max
      - sensor.week_min
      - sensor.week_max
      - sensor.month_min
      - sensor.month_max
      - sensor.cpu_temperature 
      - sensor.disk_use_percent_mnt_drive
      - sensor.memory_use_percent
      - sensor.db_size
      - sensor.load_5m
      - climate.caldaia
      - input_boolean.climate_command

climate:
  - platform: generic_thermostat
    name: Caldaia
    heater: input_boolean.climate_command
    target_sensor: sensor.28_041685abbeff_temperature
