- platform: onewire
  names:
    GENERATED_ID: temp_salotto

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  # If errors occur, remove degree symbol below
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: command_line
  name: DB size
  command: "ls -l /mnt/drive/hassio/home-assistant_v2.db | gawk '{print $5}'"
  unit_of_measurement: "M"
  value_template: '{{ ((value | int) / 1024 / 1024) | int }}'

- platform: systemmonitor
  resources:
    - type: load_5m
    - type: disk_use_percent
      arg: /mnt/drive
    - type: memory_use_percent

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'

- platform: statistics
  entity_id: sensor.28_041685abbeff_temperature
  name: Temp stats
  sampling_size: 1440
  max_age:
    days: 1

- platform: template
  sensors:
    max_temp:
      friendly_name: T max
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('sensor.temp_stats_mean','max_value') | float }}"
    min_temp:
      friendly_name: T min
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('sensor.temp_stats_mean','min_value') | float }}"
