- alias: 'Accensione caldaia'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.heat_on
      to: 'on'
  action:
    - service: climate.turn_on
      data_template:
        { "entity_id": "climate.caldaia" }
  
- alias: 'Spegnimento caldaia'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.heat_on
      to: 'off'
  action:
    - service: climate.turn_off
      data_template:
        { "entity_id": "climate.caldaia" }

- alias: 'Disabilitazione fascia temporanea cronotermostato'
  trigger:
    - platform: time
      at: "02:00:00"
  action:
    - service: input_boolean.turn_off
      data_template:
        { "entity_id": "input_boolean.enable_interval3" }
